---
actor_lr: 0.0005
algo_name: ActorCritic
alpha: 0.5
base: 0
batch_size: 1
critic_lr: 0.005
debug: true
entropy_lambda: 0.0001
env_name: MountainCar
experiment: Data
folder_suffix: Default
gamma: 1
gpu: 0
hyper: 0
inc: 29
log_output: term_file
max_episodes: 10000
optim: rmsprop
raw_basis: false
restore: false
save_count: 100
save_model: true
seed: 29
speed: 0
state_lr: 0.0005
summary: true
swarm: false
timestamp: 4|5|9:11:13
