---
actor_lr: 0.005
algo_name: ActorCritic
alpha: 0.5
base: 0
batch_size: 1
critic_lr: 0.001
debug: true
entropy_lambda: 0.0001
env_name: SimGlucosediscreteNS-v0
experiment: Data
folder_suffix: Default
gamma: 1
gpu: 0
hyper: 0
inc: 21
log_output: term_file
max_episodes: 10000
optim: rmsprop
raw_basis: true
restore: false
save_count: 100
save_model: true
seed: 21
speed: 0
state_lr: 0.001
summary: true
swarm: false
timestamp: 4|20|21:24:56
