---
actor_lr: 0.0001
algo_name: ActorCritic
alpha: 0.5
base: 0
batch_size: 1
critic_lr: 0.0005
debug: true
entropy_lambda: 0.0001
env_name: MEDEVAC
experiment: Data
folder_suffix: Default
gamma: 1
gpu: 0
hyper: 0
inc: 28
log_output: term_file
max_episodes: 10000
optim: rmsprop
raw_basis: true
restore: false
save_count: 100
save_model: true
seed: 28
speed: 2
state_lr: 0.0005
summary: true
swarm: false
timestamp: 4|20|20:34:28
